_3PAPISID=I-llRGMaoFtf4fz0/AhjDuvyUnTn8bws_7
_3PSID=LQgmumZmFgFfZBJBY-kM0cig95m_YYR2CbpaDlZyqijWsoyyquC3Vf6mALcUR1IRMAbCGA.
GENIUS_API_KEY=DiNYpg2cZAG711NUhHI4j4ZOqEw8Pfd3zVKXiVJjlmot0pucG9aNOcaD10YmP8xJ
GOOGLE_API_DAILY_QUOTA=10001
BASE_OATH_TOKEN=BQBpAFACZhkNGClb9tbFH-eXBsPEzJbjDL4AF7BAhJf_lp1zty6KUA1EM5lQYGxrn4hoE9kfEW16Ylp_menf6v16IZxPbttxTPCmHxMfow95Q7BW9o6PB5e0yx-chbuZgkdWdL2whIM_T67mGaauM3iNNCWaY_ecYr6fC0wsvxb1OqmcMnH1_Ap54-v5-WSy
BOT_NAME=JavKing
BOT_SITE=http://zenpai.herokuapp.com/projects/JavKing/home.html
CLIENT_ID=676672920625610753
CLIENT_REDIRECT=http://localhost:8080/guild-member-login-callback
CLIENT_POST_REDIRECT=http://zenpai.herokuapp.com/projects/JavKing/src/players/dashboard.html
CLIENT_SECRET=k8qPC20ASI2yq7aFe2v6PvV4Sws4vPDk
HEX=0xddaedb
MIN_VOLUME=1
MAX_VOLUME=500
MESSAGE_TIMEOUT=3
MONGO_URL=mongodb+srv://Zenpai:Kawaiiworks-1@cluster0-l6hmh.azure.mongodb.net/test?retryWrites=true&w=majority
PREFIX=~
ID_KEY=eed4c2b50ee04aecb5ff5e3994821f7d
REDIRECT_KEY=http://localhost:8080/spotify-login-callback
SECRET_KEY=3fdf113fc61a452d9a111cbe616b1e90
SOUNDCLOUD_HEX=0x89F2E3
SPOTIFY_HEX=0x55D46B
TOKEN=Njk0NjU1NTIyMjM3OTcyNTEw.GKlArS.C2kluLfGMXNY6NIZY5o9c1bIZRFxY-POqnUsBk
TWITCH_URI=https://www.twitch.tv/javkingzero
V3_API_KEY=AIzaSyD5ZV-xO_HALiJsI5AubR0DH_9pFKO41kI
VERSION=0.2.3a
X_RAPIDAPI_KEY=c755757ffcmsh94d4a92c3ad05e0p1b3cc1jsn91ec2aa9a951
YOUTUBE_HEX=0xFF0000
